WARNING 2023-10-02 09:54:52,632 log Not Found: /favicon.ico
WARNING 2023-10-02 09:57:33,119 log Not Found: /favicon.ico
WARNING 2023-10-02 09:58:55,767 log Not Found: /favicon.ico
WARNING 2023-10-02 09:59:03,244 log Not Found: /favicon.ico
WARNING 2023-10-02 11:04:35,169 log Not Found: /favicon.ico
WARNING 2023-10-02 11:05:13,727 log Not Found: /favicon.ico
WARNING 2023-10-02 11:06:38,493 log Not Found: /favicon.ico
WARNING 2023-10-02 11:06:39,224 log Not Found: /favicon.ico
WARNING 2023-10-02 11:06:45,745 log Not Found: /favicon.ico
WARNING 2023-10-02 11:06:53,788 log Not Found: /favicon.ico
WARNING 2023-10-02 11:08:22,735 log Not Found: /favicon.ico
INFO 2023-10-02 11:20:30,041 autoreload C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\views.py changed, reloading.
INFO 2023-10-02 11:20:30,988 autoreload Watching for file changes with StatReloader
INFO 2023-10-02 11:22:18,001 autoreload C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\views.py changed, reloading.
INFO 2023-10-02 11:22:18,770 autoreload Watching for file changes with StatReloader
WARNING 2023-10-02 11:23:05,864 log Not Found: /favicon.ico
INFO 2023-10-02 11:32:58,071 autoreload Watching for file changes with StatReloader
INFO 2023-10-02 11:34:38,558 autoreload C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\views.py changed, reloading.
INFO 2023-10-02 11:34:39,461 autoreload Watching for file changes with StatReloader
INFO 2023-10-02 12:15:25,964 autoreload C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\views.py changed, reloading.
INFO 2023-10-02 12:15:26,889 autoreload Watching for file changes with StatReloader
INFO 2023-10-02 12:22:00,751 autoreload C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\views.py changed, reloading.
INFO 2023-10-02 12:22:01,624 autoreload Watching for file changes with StatReloader
INFO 2023-10-02 12:22:05,246 autoreload C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\urls.py changed, reloading.
INFO 2023-10-02 12:22:06,001 autoreload Watching for file changes with StatReloader
WARNING 2023-10-02 12:22:29,981 log Not Found: /fecaf/documentacao
WARNING 2023-10-02 12:22:34,680 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:22:44,036 log Not Found: /fecaf/docs
INFO 2023-10-02 12:22:49,730 autoreload C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\urls.py changed, reloading.
INFO 2023-10-02 12:22:50,487 autoreload Watching for file changes with StatReloader
WARNING 2023-10-02 12:22:52,278 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:22:53,308 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:22:53,337 log Not Found: /favicon.ico
INFO 2023-10-02 12:26:26,997 autoreload C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\urls.py changed, reloading.
INFO 2023-10-02 12:26:27,884 autoreload Watching for file changes with StatReloader
WARNING 2023-10-02 12:26:32,498 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:26:32,942 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:26:33,268 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:26:33,446 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:26:33,613 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:26:34,098 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:26:34,268 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:26:34,445 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:26:34,759 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:26:35,045 log Not Found: /fecaf/docs
WARNING 2023-10-02 12:26:35,310 log Not Found: /fecaf/docs
INFO 2023-10-02 12:26:41,104 autoreload C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\urls.py changed, reloading.
INFO 2023-10-02 12:26:41,960 autoreload Watching for file changes with StatReloader
ERROR 2023-10-02 12:28:56,428 log Internal Server Error: /fecaf/docs
Traceback (most recent call last):
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\views.py", line 35, in get
    return render(request, 'documentacao.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static'. Did you forget to register or load this tag?
WARNING 2023-10-02 12:28:56,625 log Not Found: /favicon.ico
WARNING 2023-10-02 12:29:07,057 log Not Found: /favicon.ico
WARNING 2023-10-02 13:37:18,884 log Not Found: /favicon.ico
WARNING 2023-10-02 13:40:40,758 log Not Found: /fecaf/home
INFO 2023-10-02 13:43:25,970 autoreload C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\urls.py changed, reloading.
INFO 2023-10-02 13:43:26,816 autoreload Watching for file changes with StatReloader
WARNING 2023-10-02 13:46:52,178 log Not Found: /favicon.ico
WARNING 2023-10-02 13:46:58,376 log Not Found: /favicon.ico
WARNING 2023-10-02 13:47:45,734 log Not Found: /favicon.ico
WARNING 2023-10-02 13:49:40,266 log Not Found: /favicon.ico
WARNING 2023-10-02 13:50:12,277 log Not Found: /favicon.ico
WARNING 2023-10-02 14:07:39,518 log Not Found: /favicon.ico
WARNING 2023-10-02 14:08:24,914 log Not Found: /favicon.ico
WARNING 2023-10-02 14:10:23,437 log Not Found: /favicon.ico
WARNING 2023-10-02 14:10:58,051 log Not Found: /favicon.ico
WARNING 2023-10-02 14:11:33,589 log Not Found: /favicon.ico
WARNING 2023-10-02 14:20:32,752 log Not Found: /favicon.ico
WARNING 2023-10-02 14:22:22,187 log Not Found: /favicon.ico
WARNING 2023-10-02 14:22:30,353 log Not Found: /favicon.ico
WARNING 2023-10-02 14:23:14,161 log Not Found: /favicon.ico
WARNING 2023-10-02 15:17:27,233 log Not Found: /favicon.ico
WARNING 2023-10-02 15:18:13,546 log Not Found: /favicon.ico
WARNING 2023-10-02 15:29:16,543 log Not Found: /favicon.ico
WARNING 2023-10-02 15:29:18,116 log Not Found: /favicon.ico
WARNING 2023-10-02 15:29:48,136 log Not Found: /favicon.ico
WARNING 2023-10-02 15:30:12,874 log Not Found: /favicon.ico
ERROR 2023-10-02 15:31:02,379 log Internal Server Error: /fecaf/docs
Traceback (most recent call last):
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\views.py", line 35, in get
    return render(request, 'documentacao.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''media/icons8-copiar-50.png' from ''media/icons8-copiar-50.png'
ERROR 2023-10-02 15:31:15,911 log Internal Server Error: /fecaf/docs
Traceback (most recent call last):
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\Desktop\git-\IOTAPI\Main_app\views.py", line 35, in get
    return render(request, 'documentacao.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\templatetags\static.py", line 171, in do_static
    return StaticNode.handle_token(parser, token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\templatetags\static.py", line 145, in handle_token
    path = parser.compile_filter(bits[1])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lukas\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\template\base.py", line 703, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ''media/icons8-copiar-50.png' from ''media/icons8-copiar-50.png'
WARNING 2023-10-02 15:31:16,050 log Not Found: /favicon.ico
WARNING 2023-10-02 15:35:07,278 log Not Found: /favicon.ico
WARNING 2023-10-02 15:35:37,873 log Not Found: /favicon.ico
WARNING 2023-10-02 15:35:50,013 log Not Found: /favicon.ico
WARNING 2023-10-02 15:39:54,232 log Not Found: /favicon.ico
WARNING 2023-10-02 16:18:23,156 log Not Found: /favicon.ico
